apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spring-boot-grpc-service
  namespace: {{ .Values.config.namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.config.host }}
spec:
  hosts:
    - {{ .Values.config.host }}
  gateways:
    - istio-system/public-gateway
  http:
    - match:
        - port: 443
      route:
        - destination:
            port:
              number: 8080
            host: spring-boot-grpc-service
